run:
  timeout: 10m
  tests: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  goimports:
    local-prefixes: git.tesdev.io/
  govet:
    check-shadowing: true
linters:
  enable:
    - bodyclose
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocognit
    - asciicheck
    - gocyclo
      #   - gofmt isn't needed - goimports replaces it
    - goimports # gofmt + unused imports + import clustering
    - misspell
    - govet
    - megacheck
    - gochecknoinits
    - whitespace
    - scopelint
    - nakedret
    - dogsled
    - unparam
    - nolintlint
