name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  docker-student:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: environment
          push: true
          tags: ghcr.io/mykter/fuzz-training:latest

      - name: Image digest
        run: echo ${{ steps.build_push.outputs.digest }}
